name: First Workflow
on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  first_job:
    name: My first job
    runs-on: ubuntu-latest
    steps:
      - name: Greet the user
        run: |
          echo "Hello World"
          echo "Hello World 👋 from ${{ github.actor }}."
      
    
