name: Hacking Actions
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment Environment"
        required: true
        type: environment
        default: DEV
      deploymentId:
        description: "Deployment ID"
        required: false
        type: string
      apiToken:
        description: "Astro API Token"
        required: false
        type: string
          
jobs:
  echo_name:
    name: Deploy (${{ inputs.environment }})
    runs-on: ubuntu-latest
    steps:
      - name: Greet the user
        run: |
          echo "Hello ${{ vars.WHO_TO_GREET }} from ${{ github.actor }}."
          echo "Current branch is '${{ github.ref }}'."    
          echo "Current environment is '${{ inputs.environment }}'"
